

export const courseKeys = [
  "Accountancy",
  "Africana Studies",
  "Am Sign Lang Ling&Deaf Culture",
  "American Indian Studies",
  "American Studies",
  "Anthropology",
  "Arabic",
  "Art",
  "Art History",
  "Asian & Asian American Studies",
  "Asian American Studies",
  "Asian Studies",
  "Astronomy",
  "Athletic Training",
  "Biology",
  "Biomedical Engineering",
  "Business Law",
  "Business, College of (pre F24)",
  "CSU OnLine - LB ONLY",
  "Cambodian",
  "Chemical Engineering",
  "Chemistry & Biochemistry",
  "Chicano & Latino Studies",
  "Child Developmnt & Family Stds",
  "Chinese",
  "Cinematic Arts",
  "Civil Engineering",
  "Classics",
  "Communication Studies",
  "Comparative World Literature",
  "Computer Engr & Computer Sci",
  "Concurrent Enrollment",
  "Construction Engineering Mgmt",
  "Consumer Affairs",
  "Counseling",
  "Criminology & Criminal Justice",
  "Dance",
  "Design",
  "Doctor of Physical Therapy",
  "Earth Science",
  "Economics",
  "Educ Leadership Doctorate",
  "Education - Curr & Instruction",
  "Education - Early Childhood",
  "Education - Elementary",
  "Education - Secondary",
  "Education - Single Subject",
  "Education Specialist",
  "Educational Administration",
  "Educational Psychology",
  "Educational Technology",
  "Electrical Engineering",
  "Emergency Services Adm",
  "Engineering",
  "Engineering Technology",
  "English",
  "Enrollment Services",
  "Environmental Engineering",
  "Environmental Science & Policy",
  "Equity, Educ, & Social Justice",
  "Fashion Merchandising & Design",
  "Filipino",
  "Finance",
  "Food Science",
  "French",
  "Geography",
  "German",
  "Gerontology",
  "Graduate Business Admin",
  "Greek",
  "Health Care Administration",
  "Health Science",
  "Hebrew",
  "Hindi-Urdu",
  "History",
  "Hospitality Management",
  "Human Development",
  "Human Resources Management",
  "Information Systems",
  "International Business",
  "International Education",
  "International Studies",
  "Italian",
  "Japanese",
  "Journalism",
  "Kinesiology",
  "Korean",
  "Latin",
  "Liberal Arts, College of",
  "Liberal Studies",
  "Linguistics",
  "Management",
  "Marketing",
  "Mathematics",
  "Mathematics Education",
  "Mechanical & Aerospace Engr",
  "Military Science",
  "Music",
  "Natural Sciences",
  "Nursing",
  "Nutrition and Dietetics",
  "Philosophy",
  "Physical Science",
  "Physics",
  "Political Science",
  "Psychology",
  "Public Policy & Administration",
  "Recreation",
  "Religious Studies",
  "Romance German Russian Lang",
  "Russian",
  "Science Education",
  "Social Work",
  "Sociology",
  "Spanish",
  "Speech-Language-Pathology",
  "Statistics",
  "Student Development Higher ED",
  "Student Rec & Leadership",
  "Supplemental Instruction",
  "Supply Chain Management",
  "Theatre Arts",
  "Translation Studies",
  "University",
  "University Honors Program",
  "Urban Dual Credential Program",
  "Vietnamese",
  "Women's Gender Sexuality Stds"
] as const;
