// src/data/departments.ts

import { DepartmentType } from '@/types/departmentType'; // Ensure this path is correct

export const departments: DepartmentType[] = [
    { name: "Accountancy", code: "ACCT" },
    { name: "Africana Studies", code: "AFRS" },
    { name: "Am Sign Lang Ling&Deaf Culture", code: "ASLD" },
    { name: "American Indian Studies", code: "AIS" },
    { name: "American Studies", code: "AMST" },
    { name: "Anthropology", code: "ANTH" },
    { name: "Arabic", code: "ARAB" },
    { name: "Art", code: "ART" },
    { name: "Art History", code: "AH" },
    { name: "Asian & Asian American Studies", code: "AAAS" },
    { name: "Asian American Studies", code: "ASAM" },
    { name: "Asian Studies", code: "A/ST" },
    { name: "Astronomy", code: "ASTR" },
    { name: "Athletic Training", code: "AT" },
    { name: "Biology", code: "BIOL" },
    { name: "Biomedical Engineering", code: "BME" },
    { name: "Business Law", code: "BLAW" },
    { name: "Business, College of (pre F24)", code: "CBA" },
    { name: "CSU OnLine - LB ONLY", code: "OLNE" },
    { name: "Cambodian", code: "KHMR" },
    { name: "Chemical Engineering", code: "CH E" },
    { name: "Chemistry & Biochemistry", code: "CHEM" },
    { name: "Chicano & Latino Studies", code: "CHLS" },
    { name: "Child Developmnt & Family Stds", code: "CDFS" },
    { name: "Chinese", code: "CHIN" },
    { name: "Cinematic Arts", code: "CINE" },
    { name: "Civil Engineering", code: "C E" },
    { name: "Classics", code: "CLSC" },
    { name: "Communication Studies", code: "COMM" },
    { name: "Comparative World Literature", code: "CWL" },
    { name: "Computer Engr & Computer Sci", code: "CECS" },
    { name: "Concurrent Enrollment", code: "XYZ" },
    { name: "Construction Engineering Mgmt", code: "CEM" },
    { name: "Consumer Affairs", code: "CAFF" },
    { name: "Counseling", code: "COUN" },
    { name: "Criminology & Criminal Justice", code: "CRJU" },
    { name: "Dance", code: "DANC" },
    { name: "Design", code: "DESN" },
    { name: "Doctor of Physical Therapy", code: "DPT" },
    { name: "Earth Science", code: "ERTH" },
    { name: "Economics", code: "ECON" },
    { name: "Educ Leadership Doctorate", code: "EDLD" },
    { name: "Education - Curr & Instruction", code: "EDCI" },
    { name: "Education - Early Childhood", code: "EDEC" },
    { name: "Education - Elementary", code: "EDEL" },
    { name: "Education - Secondary", code: "EDSE" },
    { name: "Education - Single Subject", code: "EDSS" },
    { name: "Education Specialist", code: "EDSP" },
    { name: "Educational Administration", code: "EDAD" },
    { name: "Educational Psychology", code: "ED P" },
    { name: "Educational Technology", code: "ETEC" },
    { name: "Electrical Engineering", code: "EzE" },
    { name: "Emergency Services Adm", code: "EMER" },
    { name: "Engineering", code: "ENGR" },
    { name: "Engineering Technology", code: "EzT" },
    { name: "English", code: "ENGL" },
    { name: "Enrollment Services", code: "ES" },
    { name: "Environmental Engineering", code: "ENV" },
    { name: "Environmental Science & Policy", code: "ESzP" },
    { name: "Equity, Educ, & Social Justice", code: "EESJ" },
    { name: "Fashion Merchandising & Design", code: "FMD" },
    { name: "Filipino", code: "FIL" },
    { name: "Finance", code: "FIN" },
    { name: "Food Science", code: "FSCI" },
    { name: "French", code: "FREN" },
    { name: "Geography", code: "GEOG" },
    { name: "German", code: "GERM" },
    { name: "Gerontology", code: "GERN" },
    { name: "Graduate Business Admin", code: "GBA" },
    { name: "Greek", code: "GK" },
    { name: "Health Care Administration", code: "HCA" },
    { name: "Health Science", code: "HzSC" },
    { name: "Hebrew", code: "HEBW" },
    { name: "Hindi-Urdu", code: "HIND" },
    { name: "History", code: "HIST" },
    { name: "Hospitality Management", code: "HM" },
    { name: "Human Development", code: "HDEV" },
    { name: "Human Resources Management", code: "HRM" },
    { name: "Information Systems", code: "IzS" },
    { name: "International Business", code: "IB" },
    { name: "International Education", code: "INTL" },
    { name: "International Studies", code: "IxST" },
    { name: "Italian", code: "ITAL" },
    { name: "Japanese", code: "JAPN" },
    { name: "Journalism", code: "JOUR" },
    { name: "Kinesiology", code: "KIN" },
    { name: "Korean", code: "KOR" },
    { name: "Latin", code: "LAT" },
    { name: "Liberal Arts, College of", code: "CxLA" },
    { name: "Liberal Studies", code: "LxST" },
    { name: "Linguistics", code: "LING" },
    { name: "Management", code: "MGMT" },
    { name: "Marketing", code: "MKTG" },
    { name: "Mathematics", code: "MATH" },
    { name: "Mathematics Education", code: "MTED" },
    { name: "Mechanical & Aerospace Engr", code: "MAE" },
    { name: "Military Science", code: "MzS" },
    { name: "Music", code: "MUS" },
    { name: "Natural Sciences", code: "NSCI" },
    { name: "Nursing", code: "NRSG" },
    { name: "Nutrition and Dietetics", code: "NUTR" },
    { name: "Philosophy", code: "PHIL" },
    { name: "Physical Science", code: "PHSC" },
    { name: "Physics", code: "PHYS" },
    { name: "Political Science", code: "POSC" },
    { name: "Psychology", code: "PSY" },
    { name: "Public Policy & Administration", code: "PPA" },
    { name: "Recreation", code: "REC" },
    { name: "Religious Studies", code: "RxST" },
    { name: "Romance German Russian Lang", code: "RGR" },
    { name: "Russian", code: "RUSS" },
    { name: "Science Education", code: "SCED" },
    { name: "Social Work", code: "SzW" },
    { name: "Sociology", code: "SOC" },
    { name: "Spanish", code: "SPAN" },
    { name: "Speech-Language-Pathology", code: "SLP" },
    { name: "Statistics", code: "STAT" },
    { name: "Student Development Higher ED", code: "SDHE" },
    { name: "Student Rec & Leadership", code: "SRL" },
    { name: "Supplemental Instruction", code: "SxI" },
    { name: "Supply Chain Management", code: "SCM" },
    { name: "Theatre Arts", code: "THEA" },
    { name: "Translation Studies", code: "TRST" },
    { name: "University", code: "UNIV" },
    { name: "University Honors Program", code: "UHP" },
    { name: "Urban Dual Credential Program", code: "UDCP" },
    { name: "Vietnamese", code: "VIET" },
    { name: "Women's Gender Sexuality Stds", code: "WGSS" }
];
